name: Lint and Test
on:
  pull_request:
    branches: [master]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: npm-setup
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'
      - id: audit
        run: yarn audit --groups dependencies
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - id: commit-lint
        uses: wagoid/commitlint-github-action@v4.1.9
  test:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: npm-setup
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2.1.6
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - id: install
        run: yarn install --frozen-lockfile
      - id: lint
        run: yarn lint
      - id: test
        run: yarn test
      # Test docs have been updated
      #- id: check-docs
      #  run: yarn test:doc
